version: '3'

services:
  webserver_one:
    container_name: web1
    hostname: web1
    build: ./web-server

  webserver_two:
    container_name: web2
    hostname: web2
    build: ./web-server

  load_balancer:
    container_name: load-balancer
    hostname: load-balancer
    build: ./load-balancer
    ports:
      - "443:443"

  database:
    container_name: mysql-db
    hostname: mysql-db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "supersecurepass"
    volumes:
      - ./mysql/skitter.sql:/docker-entrypoint-initdb.d/skitter.sql
      - ./mysql/data:/var/lib/mysql
      
  auth:
    image: auth
    container_name: auth
    build: ./auth
    hostname: auth

  flask:
    image: flask
    container_name: flask
    build: ./flask
    hostname: flask

#  elasticsearch:
#    image: elasticsearch
#    hostname: skits
#    container_name: skits

#  node:
#    container_name: node
#    hostname: node
#    build: ./nodeJS
#    working_dir: /home/node/app
#    environment:
#      - NODE_ENV=production
#    volumes:
#      - ./nodeJS:/home/node/app
#    command: "npm start"
