version: '3'

services:
  webserver_one:
    container_name: web1
    hostname: web1
    build: ./web-server
    #   ports:
    #  - "81:81"

  webserver_two:
    container_name: web2
    hostname: web2
    build: ./web-server
    #ports:
    #  - "82:81"

  load_balancer:
    container_name: load-balancer
    hostname: load-balancer
    build: ./load-balancer
    ports:
      - "80:80"

  database:
    container_name: mysql-db
    hostname: mysql-db
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "supersecurepass"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/skitter.sql:/docker-entrypoint-initdb.d/skitter.sql
      - ./mysql/data:/var/lib/mysql
      
  auth:
    image: auth
    container_name: auth
    build: ./auth
    hostname: auth
    ports:
      - "8080:8080"
