version: '3'

services:
  webserver_one:
    container_name: web1
    hostname: web1
    build: ./web-server
    ports:
      - "81:8080"

  webserver_two:
    container_name: web2
    hostname: web2
    build: ./web-server
    ports:
      - "82:8080"

  load_balancer:
    container_name: load-balancer
    hostname: load-balancer
    build: ./load-balancer
    ports:
      - "80:80"

  database:
    container_name: mysql-db
    hostname: mysql-db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "supersecurepass"
    volumes:
      - ./mysql/skitter.sql:/docker-entrypoint-initdb.d/skitter.sql
      - ./mysql/data:/var/lib/mysql
