version: '3'
services:
  database:
    container_name: mysql-db
    hostname: mysql-db
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "supersecurepass"
    volumes:
      - ../mysql/skitter.sql:/docker-entrypoint-initdb.d/skitter.sql
      - ../mysql/data:/var/lib/mysql